version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - '11435:11434'
    volumes:
      - ./ollama_data:/root/.ollama
    container_name: ollama

  chroma:
    image: chromadb/chroma:latest
    ports:
      - '8000:8000'
    volumes:
      - ./chroma_data:/chroma/.chroma/index
    container_name: chroma
