name: Assert New PR Is Valid Action

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Clean install dependencies
        run: npm ci

      - name: Check ESLint
        run: npm run lint

      - name: Check Unit Tests
        run: npm run test:unit

      - name: Check Build
        run: npm run build
